### ISSUE TITLE
Adding bunch of new regexes

### ISSUE THREAD

**Issue by DanielAzulayy** [brootware/PyRedactKit#42]
Instead of the `Identifier` class, please consider making a new JSON (ex. regex.json) file containing a bunch of regexes in order to identify much more sensitive data in files.

Adding a bunch of regexes to a class isn't a best practice and it's tedious, we already have it premade for us.

Regexes can be taken from: https://github.com/bee-san/pyWhat/blob/5c36850447f3346d7e84b31067dfe866dc3cc3bc/pywhat/Data/regex.json

I have no problem creating a new PR for this if you want.

**Comment by brootware** [comment]
Hey @DanielAzulayy , thank you for the suggestion. Yes, totally understand about this. I recently added -c flag for users to define [custom regex pattern with json](https://github.com/brootware/PyRedactKit/blob/main/custom.json) that they want to be supplied during the redaction. You can simply do this by doing

```bash
pyredactkit -f file -c custom.json
```

Will that be something you're looking for?

**Comment by DanielAzulayy** [comment]
Hey, I looked at the -c flag, nice 
Just thought it would be useful to provide what I have mentioned by default (100+ regexes) so there will be a better chance to find more things.
Anyways -c flag is also good as well

**Comment by brootware** [comment]
> Just thought it would be useful to provide what I have mentioned by default (100+ regexes) so there will be a better chance to find more things.

This is a good idea actually. In this case, could you provide these into the custom json file instead ? Please do open a PR for this. Thank you and really appreciate the suggestion 😄

**Comment by DanielAzulayy** [comment]
Hey, sure no problem :)
I just did a new PR with the updated custom JSON file, let me know if you noticed any new bugs after adding more patterns
